### PR TITLE
Ping tool

### PR DESCRIPTION
**Pull request by gorhinstroebel**
This Ping Tool now uses Windows Socket Version 2

### CODE REVIEW

**Comment by shaunroselt** [comment]
Thanks @gorhinstroebel 

Can you post some screenshots of how it looks and works please?

**Comment by gorhinstroebel** [comment]
You can put in a domain name

image

or IP v4 Address (still working on support for IPv6)

image

**Comment by gorhinstroebel** [comment]
The entire frame will contain more ways to gather information using the ping tool, for now it's just normal ping to see if sites etc. are responding and online.

**Comment by gorhinstroebel** [comment]
Returns more statistics once a website has been successfully pinged.

The gathered statistics include:

Address: The IP address/ or hostname of the target host in string format. (if IP address was entered it returns the host name and visa versa)
RoundTripTime: The round-trip time for a ping request-response message, in milliseconds. (Response Time)
Data Size: The size of the data sent in the ping request, in bytes.
Replies Received: The number of successful ping replies received from the target host.

Another value is also returned and that is the "Status" if the host was able to be pinged it returns a value of "0" (True) in the Display it will be Shown as "Status: Online" if it returns a value of "1" (False) then the Ping request was unsuccessful, meaning statistics can't be gathered cause the host is offline.

This should be very helpful for many people. I will continue to try to enhance the Tool. Lets keep improving!

image

**Comment by shaunroselt** [comment]
@gorhinstroebel What icon do you want for the Ping Tool?

**Comment by shaunroselt** [comment]
> @gorhinstroebel What icon do you want for the Ping Tool?

Hey @gorhinstroebel 

I never got a reply on this. 

- I'm adding it to the menu for so long.
- I've decided to use the [wifi icon](https://icons.getbootstrap.com/icons/wifi/) for it. 
- I also added it under a new `Other` category in the menu.
- And lastly, I'm calling it "Ping IP / Domain"... for now. I'm not completely sold on the name yet.

This is how it looks in the menu:

Roselt Developer Tools Navigation Menu with Ping IP / Domain open


I added it in this commit: https://github.com/shaunroselt/Roselt-Developer-Tools/commit/e7f0141c9e0c32d78821336bc5069222755c4569


Will merge the actual ping tool later 🙂

**Pull request merged**
