### PR TITLE
Create Csv To Json Convertor

### PR DESCRIPTION
**Pull request by gorhinstroebel**
This tool converts CSV into JSON.

### CODE REVIEW

**Comment by gorhinstroebel** [comment]
The update code has a new function JSONToCSV that takes a string representation of a JSON array and converts it into a
CSV string. The function does the following steps:

1. Parses the JSON string into a TJSONArray using the TJSONObject.ParseJSONValue method.
2. Creates a TStringList object to store the lines of the CSV string.
3. Iterates through each JSON object in the JSON array using a for loop.
4. For each JSON object, it creates an array of strings named Fields with the same length as the number of pairs in the
JSON
object.
5. For each pair in the JSON object, it assigns the value of the pair to the corresponding index in the Fields array.
6. Joins the fields in the Fields array into a comma-separated line using the string.Join method.
7. Adds the line to the TStringList object.
8. After all JSON objects have been processed, it returns the text of the TStringList object as the result of the
method.
9 . Finally, the TStringList object is freed to avoid memory leaks.

This code assumes that the JSON string input represents a JSON array with objects that have string values for each of
their keys. The output CSV string will have one line for each JSON object in the array and the values of each object
will be separated by commas.

image

**Comment by shaunroselt** [comment]
The example screenshot with the conversion you sent is a bit confusing also:
image

Maybe you attached the wrong screenshot?

With that given JSON that you have there in the screenshot:
```JSON
[
  {"0":"0"},
  {"0":"Home"}
]
```

I would expect the CSV Output to look different than what you provided. Wouldn't it maybe convert to this instead (or something like this):
```CSV
0,0
0,Home
```

**Comment by shaunroselt** [comment]
Also, what if someone doesn't use a comma delimited string? What if they use or want a semi-colon delimited CSV string?

How would this work?

**Comment by gorhinstroebel** [comment]
I'm closing this PR. I'll make a new one.

**Comment by shaunroselt** [comment]
> I'm closing this PR. I'll make a new one.

New PR Link: https://github.com/shaunroselt/Roselt-Developer-Tools/pull/15

**Pull request closed without merging**
